### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "ea52a02ffe5139ec3df573e43426d571f6e823d9";
          sha256 = "00xf8bqpayp2xjj520s1asdbd7x31q5m6lfi6q3akic72i8k3mfd";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.13.1";
  selection = 
  {
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/v0.14.3.tar.gz";
        sha256 = "0nmydvlbw124c0qz80fx1rpggpr00ylp2zpnyn26qf1a0pfw0kg3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.14.3";
        hash = "sha256:1v61rsyfwkpla41ga6hsagzjihmn1lg5whg2gwb01w9xhdy95qd2";
      };
    };
    base-bigarray = 
    {
      pname = "base-bigarray";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bigarray/base-bigarray.base";
        hash = "sha256:1hgfwxh4vdv21m2a4g506y27pcv912v67qi4svrn53rgc43ckv6b";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    biniou = 
    {
      pname = "biniou";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/biniou/releases/download/1.2.1/biniou-1.2.1.tbz";
        sha256 = "0da3m0g0dhl02jfynrbysjh070xk2z6rxcx34xnqx6ljn5l6qm1m";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/biniou/biniou.1.2.1";
        hash = "sha256:1m9s9v4zr7022k6d50482qq7w41fdqp58nkpfhcp8574hg65kh69";
      };
    };
    cinaps = 
    {
      pname = "cinaps";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/cinaps/archive/v0.15.1.tar.gz";
        sha256 = "0w3125jfwckvmd3dx3r0qx7hj9kahdi9nqf3cqsv19nqymq8xq8v";
      };
      opamInputs = 
      {
        inherit (selection) re ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cinaps/cinaps.v0.15.1";
        hash = "sha256:01ycwfmid8zkir81g425dvjnjfdd58z2zjxig0aqwxgdxc139931";
      };
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/cmdliner/releases/cmdliner-1.0.4.tbz";
        sha256 = "1h04q0zkasd0mw64ggh4y58lgzkhg6yhzy60lab8k8zq9ba96ajw";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.0.4";
        hash = "sha256:05qlm4yp6124w2z10dpdchldfrmgmcr6h31rnxp8qs8mk0xzx48z";
      };
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz";
        sha256 = "0lxy4xkkkwgs1cj6d9lyzsqi9f6fc9r6cir5imi7yjqrpd86s1by";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.8";
        hash = "sha256:0pzd8irqkkkpfgw8nq9d21z9rj5m3qlzixyb7ybfy4b1fwh3n8bp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
        sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.1";
        hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.0.3";
        hash = "sha256:18i03m36vrfb1lnaxqacrdqc8ihff4qalrgmgym9xp37ah500d6j";
      };
      buildInputs = lib.optional self.pkgs.stdenv.isDarwin (with self.pkgs.darwin.apple_sdk.frameworks; [
        Foundation
        CoreServices
      ]);
    };
    dune-rpc = 
    {
      pname = "dune-rpc";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = 
      {
        inherit (selection) csexp xdg stdune pp ordering ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-rpc/dune-rpc.3.0.3";
        hash = "sha256:02q5pfi29j9b9nm67vqpsvp5ljhcyk524msi2ni0bdwjc7b883sd";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.0.3";
        hash = "sha256:0n0yvk2r99yk1lih3fhaqh2smlhh6nsjhxgmbjrwm9qspvv3bl27";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.0.3";
        hash = "sha256:1y1f6fabs4r5pyb1p5yvnb5sy12shqviaqq10xg9kwwimxqqyyj4";
      };
    };
    dyn = 
    {
      pname = "dyn";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dyn/dyn.3.0.3";
        hash = "sha256:02q5pfi29j9b9nm67vqpsvp5ljhcyk524msi2ni0bdwjc7b883sd";
      };
    };
    easy-format = 
    {
      pname = "easy-format";
      version = "1.3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/easy-format/releases/download/1.3.2/easy-format-1.3.2.tbz";
        sha256 = "09hrikx310pac2sb6jzaa7k6fmiznnmhdsqij1gawdymhawc4h1l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/easy-format/easy-format.1.3.2";
        hash = "sha256:0rjgw1ygf8khwb7vgl5vnw907m8b5mpkb0bnlqiqz9zfmfb4jd47";
      };
    };
    either = 
    {
      pname = "either";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/either/releases/download/1.0.0/either-1.0.0.tbz";
        sha256 = "112qa1zdkf4mvn6932jb2rwxdcvfm7lg2zgh2mr7pvid67ilsrxz";
      };
      opamInputs = {
                     inherit (selection) dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/either/either.1.0.0";
        hash = "sha256:1qcj3zl0hjlc4djn5q6qjiagm5xq1q1vgbshwlf4gj7h7kzx11bf";
      };
    };
    fiber = 
    {
      pname = "fiber";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = 
      {
        inherit (selection) stdune ocaml dyn dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fiber/fiber.3.0.3";
        hash = "sha256:0cbl2jm6vd84vfmd8m7har8awb1h2kibvzzc82gkba5z5d1a6w6f";
      };
    };
    fix = 
    {
      pname = "fix";
      version = "20220121";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/fix/-/archive/20220121/archive.tar.gz";
        sha256 = "1bd8xnk3qf7nfsmk3z6hksvcascndbl7pp2a50ndj8hzf7hdnfwm";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fix/fix.20220121";
        hash = "sha256:1b77pgcxl0ra4z28vg4azr3rraq5caaind4xz5yn4c4grkhv6nrw";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/jane-street-headers-v0.14.0.tar.gz";
        sha256 = "028yxb4h3iy025iy89v8653m5brh7flrjshghs4x99pd690pmfs7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.14.0";
        hash = "sha256:1w6zjjmyszk9pax139rkxb3vx0w23w0pfd46bddfyfkxq2rbwsvf";
      };
    };
    jsonrpc = 
    {
      pname = "jsonrpc";
      version = "development";
      src = self.directSrc "jsonrpc";
      opamInputs = 
      {
        inherit (selection) ocaml dune;
      };
      opamSrc = "jsonrpc.opam";
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/jst-config/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "0wdjs0lvc5wbggh27cf490jarfibrrb5xxsrigg41m32kjkbijm4";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppx_assert ocaml dune-configurator dune
        base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.14.1";
        hash = "sha256:0myym84b9yx4vqa0ml0zf3cx6rms3g5dv704vhf5bpr7jnqz0qcb";
      };
    };
    lsp = 
    {
      pname = "lsp";
      version = "development";
      src = self.directSrc "lsp";
      opamInputs = 
      {
        inherit (selection) yojson uutf stdune ppx_yojson_conv_lib ocaml
        jsonrpc dyn dune;
      };
      opamSrc = "lsp.opam";
    };
    menhir = 
    {
      pname = "menhir";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20211128";
        hash = "sha256:008frbinlbbv8ax0p3mzzwag7hlnpphng48va4mvjsmv8kdlll18";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20211128";
        hash = "sha256:0qh7q4p9bwzaxi1fqa2wqwm3zgq90894rw68z7l222lmi1r79hky";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20211128";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211128/archive.tar.gz";
        sha256 = "0ws71xa834l75gxs33yh9f99r6b5h0rbszmdbpqip3dn5cgj1jfc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20211128";
        hash = "sha256:0lmwvn6drhak1fwiphcsynsavwxahgq1447qj8jy2l23lccni7g7";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.13.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.13.1";
        hash = "sha256:12aajj2hc636jr6wbv4vba8pmjdndbcvnw7q35gj4agxmrjspziw";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.13.1.tar.gz";
        sha256 = "1i7ad8lh5l74wb3yzmhlv529wc75a5sjybzkad7wdl8zrj47jk0r";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.13.1";
        hash = "sha256:069i5vsndd9lsvdm5wk898nfnc85ww7459nibjg6881ww43w8ck1";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-lsp-server = 
    {
      pname = "ocaml-lsp-server";
      version = "development";
      src = self.directSrc "ocaml-lsp-server";
      opamInputs = 
      {
        inherit (selection) yojson xdg uutf stdune spawn result re
        ppx_yojson_conv_lib pp ordering omd octavius ocamlformat-rpc-lib
        ocaml fiber dyn dune-build-info dune dune-rpc csexp cmdliner;
      };
      opamSrc = "ocaml-lsp-server.opam";
    };
    ocaml-version = 
    {
      pname = "ocaml-version";
      version = "3.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocurrent/ocaml-version/releases/download/v3.4.0/ocaml-version-v3.4.0.tbz";
        sha256 = "09cavcmla9zyqj3vmmp4n59bgj1ydbk4qhsz1dqvgsyqx2svxhfq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-version/ocaml-version.3.4.0";
        hash = "sha256:18ixm46gxssqcljvjyz3yj65jphbs3jf9v998bbfm06m3y49z038";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.1.tar.gz";
        sha256 = "0ml2y3dqhhbwlf94l3jgz6gfhhfp41qaf1sjm8p8c37q1vzpj4jf";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.1";
        hash = "sha256:04ws6wbbsv56r4b6f29514inn77d91gb6sa8z62bxkswk1s1r1fn";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.3";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.3.tar.gz";
        sha256 = "0hfcwamcvinmww59b5i4yxbf0kxyzkp5qv3d1c7ybn9q52vgq463";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.3";
        hash = "sha256:1wq1lkw3rpgilprlakznsxxf60mcidn3fzi3vjrgjdrnnp9hvh19";
      };
    };
    ocamlformat-rpc = 
    {
      pname = "ocamlformat-rpc";
      version = "development";
      src = self.directSrc "ocamlformat-rpc";
      opamInputs = 
      {
        inherit (selection) uutf uuseg stdio re odoc-parser ocp-indent
        ocamlformat-rpc-lib ocaml-version ocaml menhirSdk menhirLib menhir
        fpath fix either dune-build-info dune cmdliner base;
      };
      opamSrc = "ocamlformat-rpc.opam";
    };
    ocamlformat-rpc-lib = 
    {
      pname = "ocamlformat-rpc-lib";
      version = "development";
      src = self.directSrc "ocamlformat-rpc-lib";
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp;
      };
      opamSrc = "ocamlformat-rpc-lib.opam";
    };
    ocp-indent = 
    {
      pname = "ocp-indent";
      version = "1.8.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocp-indent/archive/1.8.1.tar.gz";
        sha256 = "0rqcvwzpwwzwqvrzg1l37jjiglrk2ijgjg1c7vy3xvc8lk9zyysw";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml dune cmdliner base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocp-indent/ocp-indent.1.8.1";
        hash = "sha256:08xqzlh3xp4xs613ypy9aaflyv8zfzjjgwl1bs7zbknlgp3xbng9";
      };
    };
    octavius = 
    {
      pname = "octavius";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/octavius/archive/v1.2.2.tar.gz";
        sha256 = "1bg0fcm7haqxvx5wx2cci0mbbq0gf1vw9fa4kkd6jsriw1611jga";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/octavius/octavius.1.2.2";
        hash = "sha256:0bagilkanfjyi56hrk9dw43xs6zry9p8n3l55r3d58v5hz2xsbwl";
      };
    };
    odoc-parser = 
    {
      pname = "odoc-parser";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/odoc-parser/releases/download/1.0.0/odoc-parser-1.0.0.tbz";
        sha256 = "18bsdql39nar0k8mfvafczrkqw8dv8gdmi7b5fdsvsx9f7m0iamn";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/odoc-parser/odoc-parser.1.0.0";
        hash = "sha256:089fhf57wh7an4hgl88smgi4fdzy8yb95c3bhj15m7pvsy9h3sdf";
      };
    };
    omd = 
    {
      pname = "omd";
      version = "1.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/Chris00/omd/releases/download/1.3.1/omd-1.3.1.tar.gz";
        sha256 = "1sgdgzpx96br7npj8mh91cli5mqmzsjpngwm7x4212n3k1d0ivwa";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml base-bytes
        base-bigarray;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/omd/omd.1.3.1";
        hash = "sha256:09fzyagdfcj1b2bwj5hacbda9lldicd0a59sac5j5nls8x8rsgcc";
      };
    };
    ordering = 
    {
      pname = "ordering";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ordering/ordering.3.0.3";
        hash = "sha256:1la4jq6hkji9mxifnmmcdvhzvp2k8z0naspja6abwi5lgfnrfv56";
      };
    };
    pp = 
    {
      pname = "pp";
      version = "1.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/pp/releases/download/1.1.2/pp-1.1.2.tbz";
        sha256 = "0mhxmzsraid4yw18zr6pyjfrhvf873ls8vfd1yapdfxijs6yk974";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pp/pp.1.1.2";
        hash = "sha256:1mdh8npl8ma5ypafp6bzhjxim2if3ygny7nm0rb5689x40b1c83b";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_assert-v0.14.0.tar.gz";
        sha256 = "1l2rr4jz2q5b35ryn2z146z7m9v6k8krp5gpn8ilib66mnz5zx15";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.14.0";
        hash = "sha256:1ry1bqssjw5lc7h0x2cc7f8rmz807j5l7029lxd4i12vgq91x5km";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_base-v0.14.0.tar.gz";
        sha256 = "0b7a3fmi90jk8paz0g36yzaq670fbnrbi1j8r5ibh9wbcfli7ji6";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_js_style ppx_hash
        ppx_enumerate ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.14.0";
        hash = "sha256:1n66x8xl2n0qbq1g0b1l3nsdqlb3czj5w509riwqdgz11fyrzi25";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_cold-v0.14.0.tar.gz";
        sha256 = "1madfzhpir9amnxmg530n70vll0jrl59vyp71miji73i6b9sy6n2";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.14.0";
        hash = "sha256:0g566vskiblrxr246c3s26rlzxciln518fr4f6d8lid63qgrgnfm";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_compare-v0.14.0.tar.gz";
        sha256 = "0mqxa2s194nif7x4fjn1p5gd9i3bakr8nv27gf8x1g5nmi8q9pmp";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.14.0";
        hash = "sha256:1ndfsgazb7yg5q3aqzcrnr914sf615bsh4z4q202bdvpf0fqj31k";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_enumerate-v0.14.0.tar.gz";
        sha256 = "1ij6sffgqhnjwnj9brhrrw1c6xgxlh0s6r17x1qkgnyrc73gfsz8";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.14.0";
        hash = "sha256:0lgnrpq1vmb44367y7mdr7jw1yqmy08fi6phgq8pch3a47fdk2rm";
      };
    };
    ppx_expect = 
    {
      pname = "ppx_expect";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_expect/archive/v0.14.2.tar.gz";
        sha256 = "1gcjlya6knnsrl60sd3vlgp7arj39xm5fjjfk5sick4z66agm2n5";
      };
      opamInputs = 
      {
        inherit (selection) stdio re ppxlib ppx_inline_test ppx_here ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_expect/ppx_expect.v0.14.2";
        hash = "sha256:14hnawvs9fc87kghg00zj0p1p21f22gdy1767l2nwb4ihl3h133b";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_hash-v0.14.0.tar.gz";
        sha256 = "0x4wgdvhgd8a49bzari52jpkykxpv6ncgp5ncda3xgg0a9r49s8n";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.14.0";
        hash = "sha256:0zcnsd0724w6kpx4w1i3nbfrvffhnqjn3rinddgqjndx5pvghrlc";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_here-v0.14.0.tar.gz";
        sha256 = "0b444djy68v6ji0ypwv5l02pkl151qzrgg96lyhl8dxfrzvj1zkj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.14.0";
        hash = "sha256:0f7p619ymqm27iclcx3cbyyn1k0mccw9vsa0l88m1jk3kjgjbmzz";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_inline_test/archive/v0.14.1.tar.gz";
        sha256 = "0qzvm8rg07annl8zpqlhzx1z8ahrrf02r1brd43ykqas5sww3rfp";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.14.1";
        hash = "sha256:1vwg8bgw093ia075n7vh0kl82sjd5r9yk27s45ljzz9cmfqrr4sa";
      };
    };
    ppx_js_style = 
    {
      pname = "ppx_js_style";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_js_style/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "1nq4rj659f34dc28pj7ir2szqbpky4nzs9qfw0am6sf36jwispiw";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib octavius ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_js_style/ppx_js_style.v0.14.1";
        hash = "sha256:05bc07ghvfd4d85inf1qvpqxphvcg7mgf8fn9ycib6fdmxdkkamq";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_optcomp/archive/v0.14.3.tar.gz";
        sha256 = "0bxzh0pm3zdiadrd37jjzp7zm2qn28mx25ahk0shgfb73vya809n";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.14.3";
        hash = "sha256:0xh7m3hsm7vrhzmd86n3irhydp9lyr23ax9mg1khq2jhcbyqqvy0";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.3.tar.gz";
        sha256 = "0fbnkhsd6yphc49pa21nlmbik99n7qkaz8l9paq96v012ipg9h9g";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.3";
        hash = "sha256:0f1bxwrzykh72b7dzjqn4bydcmfli6bnd19wmwqw2z6n0y9crz41";
      };
    };
    ppx_yojson_conv = 
    {
      pname = "ppx_yojson_conv";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_yojson_conv-v0.14.0.tar.gz";
        sha256 = "0ls6vzj7k0wrjliifqczs78anbc8b88as5w7a3wixfcs1gjfsp2w";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_yojson_conv_lib ppx_js_style ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv/ppx_yojson_conv.v0.14.0";
        hash = "sha256:08awq9hgbbxvr9321m24jxlm3zixwxk9pbk8xv5asglx01dr5ydl";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_yojson_conv_lib-v0.14.0.tar.gz";
        sha256 = "1f1530pvyg05zwi83iwrk3v207w316wlljikwyl9ahjh24lsja46";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.14.0";
        hash = "sha256:0zg2d8aiflyjs2pcvg509c47gg6d64rk010pflszp19dw9zp1hha";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.25.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.25.0/ppxlib-0.25.0.tbz";
        sha256 = "1m8bhw9adzdyh5zfddw6r5qvw03nlq2zfm6jg32mv10mfw71abrd";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.25.0";
        hash = "sha256:0l9rjdc91kklyw39dl5ff6gxvlgd1kry2fgm89vjm83i437lwa2c";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.10.3/re-1.10.3.tbz";
        sha256 = "1fqfg609996bgxr14yyfxhvl6hm9c1j0mm2xjdjigqrzgyb4crc4";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.10.3";
        hash = "sha256:1f2xgscc07g800ia8z43i1p377dj2fjdrpzsqgzvw1dnplwnklya";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.14.0";
        hash = "sha256:0k9vkjbiibja48c0yayal7xwyik3h3c3v4dwd3j7jbmras63ig2c";
      };
    };
    spawn = 
    {
      pname = "spawn";
      version = "v0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/spawn/archive/v0.15.0.tar.gz";
        sha256 = "1isppdyahdcdv8agw1w1l3hyl6kwsbcspjw2h5rlrxn71ajv43ri";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/spawn/spawn.v0.15.0";
        hash = "sha256:1zfg8d644i2pdq90jwblpi0y8k7xim4xb8i11czpv1qjw2p0s1y1";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/stdio-v0.14.0.tar.gz";
        sha256 = "1hj5hraprqy2i90a690l11yjszvb99j818q3d684ryx6p2lddk0l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.14.0";
        hash = "sha256:19hlf6bgx1avq4ifwji2rj2f2j26v3nf8ywjnwh2m3dpvfqc4pvk";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stdune = 
    {
      pname = "stdune";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dyn dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdune/stdune.3.0.3";
        hash = "sha256:1r7ahag8zpwqz8796d04702jfvw3m1a5iwzrvir7sk08ibd59k39";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/time_now-v0.14.0.tar.gz";
        sha256 = "0hkn2jw4dz5gflnsblskl5wp6z7zbrahwjmaxmsskfviwjg82cqh";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.14.0";
        hash = "sha256:1s8bqbks0cjw4x68nn5xlkykn3bcqh2rmrx6hgs53dalkiqv7ry0";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.5.tbz";
        sha256 = "1iyinmcfqpprk7k4cc51nqgypayprbj4larwcfqw86k5dri84825";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.5";
        hash = "sha256:04vg4zic7f6zk44vkvqw2fcr562hl7d0gklv3vgphk4n3bnqbcyy";
      };
    };
    uucp = 
    {
      pname = "uucp";
      version = "14.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uucp/releases/uucp-14.0.0.tbz";
        sha256 = "1yx9nih3d9prb9zizq8fzmmqylf24a6yifhf81h33znrj5xn1mpj";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        uunf = selection.uunf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uucp/uucp.14.0.0";
        hash = "sha256:03h0lnfnb4sad9lndnv8p5ylpwvp8gzqs9dk3v3cz9vz156fi99d";
      };
    };
    uuseg = 
    {
      pname = "uuseg";
      version = "14.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uuseg/releases/uuseg-14.0.0.tbz";
        sha256 = "1g9zyzjkhqxgbb9mh3cgaawscwdazv6y8kdqvmy6yhnimmfqv25p";
      };
      opamInputs = 
      {
        inherit (selection) uucp topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuseg/uuseg.14.0.0";
        hash = "sha256:0j96m881gh80g7sfy8va4l2w7gmijv7dznk38ndl33k6pyhdikna";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    xdg = 
    {
      pname = "xdg";
      version = "3.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.3/fiber-3.0.3.tbz";
        sha256 = "0bvkwm0nqs74gwanfcd7xind8c9fdwwdgzzvmsfdkw2q2sd4j16m";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xdg/xdg.3.0.3";
        hash = "sha256:1qsbgr6vgrixcczgwbxwcjnrd237dvrb157x6jya8mjkpw7fd9ig";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "1.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/1.7.0/yojson-1.7.0.tbz";
        sha256 = "1iich6323npvvs8r50lkr4pxxqm9mf6w67cnid7jg1j1g5gwcvv5";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune cppo biniou;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.1.7.0";
        hash = "sha256:1n8iih0jmaf9b0hsv6ph729jajws9w43kgm24324p4wlj45rjs2q";
      };
    };
  };
}

