version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - no changelog
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - no changelog
