(env
 (_
  (env-vars
   (OCAMLLSP_TEST true)
   (LEV_DEBUG 1))))

(library
 (name ocaml_lsp_e2e)
 (inline_tests
  (enabled_if
   (= %{os_type} Unix))
  (deps
   %{bin:ocaml-index}
   %{bin:ocamlformat-rpc}
   for_ppx.ml
   for_pp.ml
   (package ocaml-lsp-server)))
 (libraries
  unix
  stdune
  dune-rpc
  fiber
  fs-io
  yojson
  re
  xdg
  ppx_yojson_conv_lib
  lev_fiber
  lev
  ocaml_lsp_server
  spawn
  jsonrpc
  lsp
  lsp_fiber
  ;; This is because of the (implicit_transitive_deps false)
  ;; in dune-project
  base
  ppx_expect.config
  ppx_expect.config_types
  ppx_inline_test.config)
 (preprocess
  (per_module
   ((action
     (run sed "s/world/universe/g" %{input-file}))
    for_pp)
   ((pps ppx_expect)
    action_extract
    action_inline
    action_open_dune
    action_mark_remove
    code_action_protocol
    code_action_resolve
    code_actions_annotations
    code_actions_destruct
    code_actions_interface
    code_actions_quick_fixes
    code_lens
    completion
    completion_resolve
    completions
    formatting
    folding_range
    range_formatting
    references
    rename
    construct
    doc_to_md
    document_flow
    document_highlight
    document_sync
    document_text_command
    exit_notification
    for_ppx
    hover
    hover_extended
    hover_ocamlformat_restart
    infer_intf
    inlay_hints
    jump_to_typed_hole
    merlin_call_compatible
    destruct
    debug_echo
    declaration
    definition
    diagnostics
    dune_connection_errors
    dune_diagnostic_aggregation
    dune_diagnostic_conversion
    dune_diagnostics
    dune_formatting
    dune_nested_root
    dune_progress
    dune_progress_lifecycle
    dune_promotion_disconnect
    dune_promotion_execute
    dune_promotion_open
    dune_promotion_shared_source
    dune_registry_errors
    dune_workspace_removal
    metrics
    ml_mli_mismatch_diagnostics
    refactor_extract
    registration_order
    semantic_hl_data
    semantic_hl_helpers
    semantic_hl_tests
    selection_range
    signature_help
    start_stop
    switch_impl_intf
    syntax_doc_tests
    test
    type_enclosing
    type_definition
    documentation
    document_symbol
    merlin_jump
    phrase
    type_expression
    typed_holes
    unsupported_requests
    locate
    locate_types
    type_search
    with_pp
    with_ppx
    workspace_change_config
    workspace_initialization
    workspace_symbol
    workspace_symbol_partial_build
    wrapping_ast_node))))
